name: "Test"
# Only execute this workflow when a PR is opened or when something is pushed to the master branch
on:
  pull_request:
    branches: [ master ]
jobs:
  test:
    # Set up OS
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Setup java and maven
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: 'gradle'
      # Setup executable gradle
      - name: Make Gradle executable
        run: chmod +x gradlew
      # Test plugin
      - name: Test Plugin
        run: ./gradlew test check --no-daemon
